#ifndef __myframe__
#define __myframe__

/**
@file
Subclass of MyFrameBase, which is generated by wxFormBuilder.
*/

#include "myframebase.h"

//// end generated include

#include <iostream>
#include <wx/dir.h>

/** Implementing MyFrameBase */
class MyFrame : public MyFrameBase
{
	protected:
		// Handlers for MyFrameBase events.
		void onInputSelect( wxFileDirPickerEvent& event );
		void onOutputSelect( wxFileDirPickerEvent& event );
		void onUnused( wxCommandEvent& event );
		void onClose( wxCommandEvent& event );
		void onRun(wxCommandEvent& event);
		void onAbout( wxCommandEvent& event );
		
	public:
		/** Constructor */
		MyFrame( wxWindow* parent );
	//// end generated class members


public:
	MyFrame(const wxString& title = wxT("test"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(621, 438) );
	void stealStdin();
	void restoreStdin();
	~MyFrame();

private:
	std::streambuf *sbOld{ nullptr };


protected:
	wxFileName outDirName;
	wxFileName inDirName;




};

#endif // __myframe__
