#ifndef __progressbar__
#define __progressbar__

/**
@file
Subclass of ProgressBase, which is generated by wxFormBuilder.
*/

#include "myframebase.h"

//// end generated include

/** Implementing ProgressBase */
class ProgressBar : public ProgressBase
{
	public:
		/** Constructor */
		ProgressBar( wxWindow* parent );
	//// end generated class members


public:
	void setProgressRange(unsigned int);
	void setProgressValue(unsigned int);
	
};

#endif // __progressbar__
